// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimperSecureOnlineTestSystem.Infrastructure.Data;

#nullable disable

namespace SimperSecureOnlineTestSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310023536_AddPracticalAssessmentModule")]
    partial class AddPracticalAssessmentModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_company");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_name");

                    b.Property<string>("Nrp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nrp");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Nrp")
                        .IsUnique();

                    b.ToTable("tbl_m_employee");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("selected_answer");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("tbl_t_exam_answer");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("log_type");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("tbl_t_exam_log");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("question_order");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique();

                    b.HasIndex("SessionId", "QuestionOrder")
                        .IsUnique();

                    b.ToTable("tbl_r_exam_question");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("PassStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("pass_status");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("tbl_t_exam_result");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VehicleId", "ScheduledAt");

                    b.HasIndex("EmployeeId", "VehicleId", "ScheduledAt")
                        .IsUnique();

                    b.ToTable("tbl_t_exam_schedule");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessPasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("access_password_hash");

                    b.Property<bool>("CameraActive")
                        .HasColumnType("boolean")
                        .HasColumnName("camera_active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ref_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TabSwitchCount")
                        .HasColumnType("integer")
                        .HasColumnName("tab_switch_count");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("tbl_t_exam_session");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GradeValue")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade_value");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("numeric")
                        .HasColumnName("numeric_value");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("TemplateItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateItemId");

                    b.HasIndex("SessionId", "TemplateItemId")
                        .IsUnique();

                    b.ToTable("tbl_t_practical_assessment_score");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<string>("FinalGrade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("final_grade");

                    b.Property<decimal?>("FinalNumericScore")
                        .HasColumnType("numeric")
                        .HasColumnName("final_numeric_score");

                    b.Property<string>("InstructorNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instructor_note");

                    b.Property<long>("InstructorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("instructor_user_id");

                    b.Property<bool?>("PassStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("pass_status");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("InstructorUserId", "ScheduledAt");

                    b.HasIndex("EmployeeId", "VehicleId", "ScheduledAt");

                    b.ToTable("tbl_t_practical_assessment");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GradeOptions")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("grade_options");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PassingGrade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passing_grade");

                    b.Property<decimal?>("PassingScore")
                        .HasColumnType("numeric")
                        .HasColumnName("passing_score");

                    b.Property<string>("ScoringMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scoring_mode");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("template_name");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CompanyId", "VehicleId", "IsActive");

                    b.ToTable("tbl_m_practical_template");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplateItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ItemLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_label");

                    b.Property<string>("SectionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_name");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("tbl_m_practical_template_item");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_d");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VehicleId");

                    b.ToTable("tbl_m_question");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_m_user_login");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SimperType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("simper_type");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vehicle_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tbl_m_vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Employee", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamAnswer", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Question", "Question")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", "Session")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamLog", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", "Session")
                        .WithMany("ExamLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", "Session")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamResult", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", "Session")
                        .WithOne("ExamResult")
                        .HasForeignKey("SimperSecureOnlineTestSystem.Domain.Entities.ExamResult", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamSchedule", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Employee", "Employee")
                        .WithMany("ExamSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ExamSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentScore", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentSession", "Session")
                        .WithMany("Scores")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplateItem", "TemplateItem")
                        .WithMany("Scores")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentSession", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", "CreatedByUser")
                        .WithMany("CreatedPracticalSessions")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Employee", "Employee")
                        .WithMany("PracticalAssessmentSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", "InstructorUser")
                        .WithMany("PracticalAssignments")
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplate", "Template")
                        .WithMany("Sessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("PracticalAssessmentSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("InstructorUser");

                    b.Navigation("Template");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplate", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Company", "Company")
                        .WithMany("PracticalAssessmentTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("PracticalAssessmentTemplates")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplateItem", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Question", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Company", "Company")
                        .WithMany("Questions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Questions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("SimperSecureOnlineTestSystem.Domain.Entities.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("PracticalAssessmentTemplates");

                    b.Navigation("Questions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("PracticalAssessmentSessions");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("ExamAnswers");

                    b.Navigation("ExamLogs");

                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamResult");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentSession", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplate", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.PracticalAssessmentTemplateItem", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Question", b =>
                {
                    b.Navigation("ExamAnswers");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.UserLogin", b =>
                {
                    b.Navigation("CreatedPracticalSessions");

                    b.Navigation("PracticalAssignments");
                });

            modelBuilder.Entity("SimperSecureOnlineTestSystem.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("PracticalAssessmentSessions");

                    b.Navigation("PracticalAssessmentTemplates");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
